export const GUIDANCE_COPY = {
  quit: 'Quitter le guidage',
  progress: (current: number, total: number) => `Étape ${current} sur ${total}`,
  listenCta: 'Écouter le guide',
  noAudio: 'Aucun guide audio pour cette étape.',
  nextStep: (name: string) => `Ensuite : ${name}`,
  walkHint: (distance: string, minutes: number) =>
    `${distance} · ~${minutes} min de marche`,
  prevStep: 'Étape précédente',
  nextStepCta: 'Étape suivante',
  finishCta: 'Terminer le parcours',
  viewPlace: 'Voir la fiche du lieu',
  viewPlaceShort: 'Fiche lieu',
  viewMap: 'Voir sur la carte',
  openMap: 'Ouvrir la carte plein écran',
  openMapShort: 'Carte plein écran',
  mapSection: 'Sur la carte',
  quitTitle: 'Quitter le guidage ?',
  quitBody: 'Votre progression est enregistrée.',
  quitConfirm: 'Quitter',
  quitCancel: 'Continuer le guidage',
  resumeTitle: 'Reprendre votre parcours',
  resumeCta: (step: number, name: string) => `Reprendre à l’étape ${step} — ${name}`,
  restartCta: 'Recommencer depuis le début',
  completedTitle: 'Parcours terminé !',
  completedSubtitle: (title: string) => `Vous avez complété ${title}`,
  backToItinerary: 'Retour au parcours',
  backToCity: (city: string) => `Retour à ${city}`,
  notFoundTitle: 'Parcours introuvable',
  notFoundBody: 'Ce parcours n’existe pas ou n’est plus disponible.',
  back: 'Retour',
  a11yScreen: (title: string) => `Guidage — ${title}`,
  a11yMap: (step: number, name: string) =>
    `Carte, étape ${step}, ${name}. Ouvrir la carte plein écran`,
} as const;
