export const PROFILE_COPY = {
  title: 'Mon compte',
  welcomeAnonymous:
    'Connectez-vous pour retrouver vos parcours et synchroniser votre expérience.',
  benefitRoutes: 'Sauvegardez vos parcours',
  benefitSync: 'Reprenez où vous en étiez sur tous vos appareils',
  loginCta: 'Se connecter',
  registerCta: 'Créer un compte',
  continueWithoutAccount: 'Continuer sans compte',
  completeProfileHint: 'Ajoutez un nom pour personnaliser votre espace',
  editProfile: 'Modifier le profil',
  save: 'Enregistrer',
  cancel: 'Annuler',
  myRoutes: 'Mes parcours',
  settings: 'Paramètres',
  history: "Historique d'écoute",
  premiumActive: 'Premium actif',
  discoverPremium: 'Découvrir Premium',
  logout: 'Se déconnecter',
  logoutTitle: 'Se déconnecter ?',
  logoutBody:
    'Vous devrez vous reconnecter pour accéder à vos parcours enregistrés.',
  logoutConfirm: 'Se déconnecter',
  sessionExpired: 'Votre session a expiré. Reconnectez-vous pour continuer.',
  loadError: 'Impossible de charger votre profil. Vérifiez votre connexion.',
  retry: 'Réessayer',
  updateSuccess: 'Profil mis à jour',
  errorGeneric: 'Une erreur est survenue. Réessayez.',
  editSheetTitle: 'Modifier le profil',
  displayNameLabel: 'Nom affiché',
  firstNameLabel: 'Prénom',
  lastNameLabel: 'Nom',
  birthDateLabel: 'Date de naissance',
  emailReadonly: 'Adresse e-mail',
  emailReadonlyHint: 'Non modifiable pour le moment',
  mockBadge: 'Mode démo',
  mockHint: 'Données locales — l’API sera branchée plus tard.',
  demoLoginCta: 'Voir le profil (démo)',
  shortcutsTitle: 'Accès rapide',
  statRoutes: 'Parcours',
  statFavorites: 'Favoris',
  statListens: 'Écoutes',
  statCities: 'Villes',
  recentRoutesTitle: 'Parcours récents',
  recentRoutesSeeAll: 'Tout voir',
  recentListensTitle: 'Dernières écoutes',
  createRouteCta: 'Composer un parcours',
  createRouteHint: 'Ajoutez des lieux depuis la carte',
  premiumCardTitle: 'NOOK Premium',
  premiumCardBodyActive: 'Tous vos parcours premium sont débloqués.',
  premiumCardBodyInactive: 'Parcours curatés et guides audio exclusifs.',
  exploreMap: 'Carte',
  discover: 'Découvrir',
  favorites: 'Favoris',
  steps: (n: number) => (n <= 1 ? `${n} étape` : `${n} étapes`),
} as const;
