export const SETTINGS_COPY = {
  title: 'Paramètres',
  sectionPreferences: 'Préférences',
  sectionNotifications: 'Notifications',
  sectionAccount: 'Compte',
  sectionLegal: 'Confidentialité et conditions',
  sectionApp: 'Application',
  language: 'Langue',
  languageFr: 'Français',
  languageEn: 'English',
  push: 'Notifications push',
  pushDescription: 'Alertes sur vos parcours et nouveautés.',
  routeReminders: 'Rappels de parcours',
  permissionDenied:
    'Autorisez les notifications dans les réglages de votre appareil.',
  openSettings: 'Ouvrir les réglages',
  email: 'Adresse e-mail',
  password: 'Mot de passe',
  changePassword: 'Modifier le mot de passe',
  changePasswordSoon: 'Bientôt disponible',
  premium: 'Abonnement Premium',
  premiumActive: 'Actif',
  premiumInactive: 'Non abonné',
  managePremium: 'Gérer mon abonnement',
  privacy: 'Politique de confidentialité',
  terms: "Conditions d'utilisation",
  location: 'Localisation',
  locationGranted: 'Autorisée',
  locationDenied: 'Non autorisée',
  version: (v: string) => `Version ${v}`,
  logout: 'Se déconnecter',
  logoutTitle: 'Se déconnecter ?',
  logoutBody:
    'Vous devrez vous reconnecter pour accéder à vos parcours enregistrés.',
  logoutConfirm: 'Se déconnecter',
  cancel: 'Annuler',
  loadError: 'Impossible de charger les paramètres.',
  saveError: 'Modification non enregistrée. Réessayez.',
  retry: 'Réessayer',
} as const;
