export const USER_ITINERARIES_COPY = {
  title: 'Mes parcours',
  follow: 'Suivre le parcours',
  viewMap: 'Voir sur la carte',
  delete: 'Supprimer',
  deleteTitle: 'Supprimer ce parcours ?',
  deleteBody: (title: string) => `« ${title} » sera définitivement supprimé.`,
  deleteConfirm: 'Supprimer',
  cancel: 'Annuler',
  emptyTitle: "Aucun parcours pour l'instant",
  emptyBody: 'Explorez la carte ou les parcours NOOK pour commencer.',
  emptyExplore: 'Explorer la carte',
  emptyDiscover: 'Découvrir les parcours',
  incompleteBadge: 'Incomplet',
  deletedToast: 'Parcours supprimé',
  loadError: 'Impossible de charger vos parcours.',
  retry: 'Réessayer',
  tooShort: 'Ce parcours ne peut pas être démarré pour l\'instant.',
} as const;
