export const USER_ITINERARIES_COPY = {
  title: 'Mes parcours',
  createHeader: 'Créer',
  createFab: 'Nouveau parcours',
  follow: 'Suivre le parcours',
  edit: 'Modifier',
  viewMap: 'Voir sur la carte',
  delete: 'Supprimer',
  deleteTitle: 'Supprimer ce parcours ?',
  deleteBody: (title: string) => `« ${title} » sera définitivement supprimé.`,
  deleteConfirm: 'Supprimer',
  cancel: 'Annuler',
  emptyTitle: "Aucun parcours pour l'instant",
  emptyBody:
    'Créez un parcours en ajoutant des lieux depuis la carte ou une fiche.',
  emptyCreate: 'Créer un parcours',
  emptyExplore: 'Explorer la carte',
  incompleteBadge: 'Incomplet',
  deletedToast: 'Parcours supprimé',
  loadError: 'Impossible de charger vos parcours.',
  retry: 'Réessayer',
  tooShort: 'Ajoutez au moins 2 lieux pour démarrer ce parcours.',
  createSoon: 'La création de parcours arrive bientôt.',
  editSoon: 'La modification de parcours arrive bientôt.',
} as const;
